### ISSUE TITLE
activer les dashboards privées

### ISSUE THREAD

**Issue by WassimDhib** [leadwire-apm/leadwire-portail#154]
* Menu custom : activer le bouton de création des dashboards privés
* Menu custom : afficher les dashboards custom (cadenas fermé)
* Watchers : afficher les dashboards privés dans la liste déroulante, marqués par ** Private **

**Comment by hameddhib** [comment]
est ce qu'il faut que je crée un tenant private ?

**Comment by WassimDhib** [comment]
il existe, chaque user a son tenant privé

**Comment by hameddhib** [comment]
est ce que l'url est bonne ou non ?

https://kibana.test.leadwire.io/app/kibana?security_tenant=tuser_tenant#/dashboard?_g=()&_a=(%20description:'',filters:!(),%20fullScreenMode:!f,options:(%20darkTheme:!f,hidePanelTitles:!%20f,useMargins:!t),panels:!(),%20query:(language:lucene,query:'%20'),timeRestore:!f,title:'',viewMode:edit)

**Comment by WassimDhib** [comment]
https://kibana.test.leadwire.io/app/kibana?security_tenant=__user__#/dashboard?_a=(description:'',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),panels:!(),query:(language:kuery,query:''),timeRestore:!f,title:'',viewMode:edit)&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))

**Comment by hameddhib** [comment]
Capture d’écran 2020-10-15 à 17.55.03![image.png](https://zube.io/files/lead-wire/ceea289f80febf13e8f31e46616883fc-image.png)

Capture d’écran 2020-10-15 à 17.55.24![image.png](https://zube.io/files/lead-wire/39a6d74f3a80bff9860bd90d810b4d10-image.png)
