### ISSUE TITLE
Report List

### ISSUE THREAD

**Issue by WassimDhib** [leadwire-apm/leadwire-portail#161]
1)les champs titre et dashbord sont parfois vides

![image](https://user-images.githubusercontent.com/30473593/81016972-be115400-8e61-11ea-8894-1efae933513e.png)

2) tous les champs en anglais
titre => Title

**Comment by hameddhib** [comment]
j'arrive pas a reproduire, comment t'as fait ?

**Comment by WassimDhib** [comment]
@hameddhib 
il faut créer des watchers et les exécuter plusieurs fois pour avoir des rapports.
Envoies moi une copie d'écran si ça s'affiche correctement sur ton environnement.

**Comment by hameddhib** [comment]
j'ai créé une dizaine et ça marche bien pour moi

Capture d’écran 2020-10-12 à 17.33.44![image.png](https://zube.io/files/lead-wire/3ced8622e348b9ea6cca347f29c215a6-image.png)

**Comment by WassimDhib** [comment]
@hameddhib 
il faut des vrais rapports (sans erreurs)

**Comment by WassimDhib** [comment]
exemple de la production : 


![image](https://user-images.githubusercontent.com/30473593/95765254-e1aeb500-0cb1-11eb-9aeb-77d40f5718c7.png)

**Comment by hameddhib** [comment]
j'ai pas réussi a faire un rapport sans erreur ( net::ERR_CONNECTION_REFUSED at http://localhost:8008 ), et un rapport en erreur ou en succès ça change rien dans le menu rapport c'est les memes données a afficher.

je l'aise de coté et on verra après si ça persiste ou non

**Comment by WassimDhib** [comment]
@hameddhib 
la configuration du conteneur leadwire-portail n'est pas correcte (l'url de Kibana n'est pas localhost:8008)
```
     LEADWIRE_KIBANA_HOST: http://leadwire_leadwire-kibana
      LEADWIRE_KIBANA_PORT: 5601
```

**Comment by hameddhib** [comment]
j'arrive pas a reproduire meme avec des rapports sans erreurs
 Capture d’écran 2020-10-15 à 14.59.20![image.png](https://zube.io/files/lead-wire/5d7294ca91d34fcfa6bc33d7f220bf78-image.png)
