### ISSUE TITLE
Class 'Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle' not found

### ISSUE THREAD

**Issue by WassimDhib** [leadwire-apm/leadwire-portail#166]
```
[root@9d016edfd617 leadwire-portail]# php bin/console debug:container --env-vars
PHP Fatal error:  Uncaught Error: Class 'Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle' not found in /usr/share/leadwire-portail/app/AppKernel.php:36
Stack trace:
#0   /usr/share/leadwire-portail/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(488): AppKernel->registerBundles()
leadwire-apm/leadwire-portail#1 /usr/share/leadwire-portail/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(132): Symfony\Component\HttpKernel\Kernel->initializeBundles()
leadwire-apm/leadwire-portail#2 /usr/share/leadwire-portail/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(64): Symfony\Component\HttpKernel\Kernel->boot()
leadwire-apm/leadwire-portail#3 /usr/share/leadwire-portail/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
leadwire-apm/leadwire-portail#4 /usr/share/leadwire-portail/bin/console(29): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
leadwire-apm/leadwire-portail#5 { in /usr/share/leadwire-portail/app/AppKernel.php on line 36
[root@9d016edfd617 leadwire-portail]#

```

**Comment by hameddhib** [comment]
comment je fais pour reproduire

**Comment by WassimDhib** [comment]
@hameddhib 
`php bin/console debug:container --env-vars`

**Comment by hameddhib** [comment]
si tu as besoin de lancer cette commande php bin/console debug:container,  
évite d'installer les dépendances avec l'option **--no-dev** comme dans l'exemple si dessous 

php /usr/share/leadwire-portail/composer.phar install --no-dev --no-scripts

l'option --no-dev ne permet pas d'installer les dépendances de dev que **sensio/generator-bundle** fait partie.

`
"require-dev": {
        "fzaninotto/faker": "^1.7",
        "kint-php/kint": "^2.2",
        "phpstan/phpstan": "^0.11",
        "phpstan/phpstan-deprecation-rules": "^0.11",
        "phpstan/phpstan-symfony": "^0.11",
        "sensio/generator-bundle": "^3.0",
        "squizlabs/php_codesniffer": "^3.3",
        "symfony/browser-kit": "^3.4",
        "symfony/css-selector": "^3.4",
        "symfony/phpunit-bridge": "^3.4",
        "theofidry/psysh-bundle": "^3.5"
    }
`
