### ISSUE TITLE
Cluster overview

### ISSUE THREAD

**Issue by WassimDhib** [leadwire-apm/leadwire-portail#175]
3 noeuds marqués comme Master, 1 seul peut être Master

![image](https://user-images.githubusercontent.com/30473593/82115269-fff3a180-9761-11ea-85b4-4c5d9789742d.png)

**Comment by WassimDhib** [comment]
GET /_cat/master

**Comment by hameddhib** [comment]
Capture d’écran 2020-10-16 à 17.35.46![image.png](https://zube.io/files/lead-wire/1a5923ce2c68668cf414aae39ae7a45e-image.png)
