### ISSUE TITLE
ajouter une destination (open distro) pour alert manager

### ISSUE THREAD

**Issue by leadwire-apm** [leadwire-apm/leadwire-portail#186]

**Comment by leadwire-apm** [comment]
```
POST _opendistro/_alerting/destinations
{
  "type": "custom_webhook",
  "name": "alertmanager_custom_webhook",
  "custom_webhook": {
    "path": "api/v1/alerts",
    "scheme": "http",
    "port": 9093,
    "host": "leadwire_leadwire-alertmanager"
  }
}
```

**Comment by hameddhib** [comment]
quand on execute cette destination ?

**Comment by WassimDhib** [comment]
@hameddhib 
C'est exécuté par la commande d'installation lorsque LEADWIRE_SETUP_CLUSTER=true

https://github.com/leadwire-apm/leadwire-portail/blob/7973d509501c6ecf33018ea9c169bfe33fe88b16/src/AppBundle/Command/InstallCommand.php#L105

**Comment by hameddhib** [comment]
Capture d’écran 2020-10-15 à 18.46.45![image.png](https://zube.io/files/lead-wire/a922362d617e92ffc6e817b2428c8062-image.png)
