### ISSUE TITLE
Liens vers Frame Kibana KO

### ISSUE THREAD

**Issue by WassimDhib** [leadwire-apm/leadwire-portail#217]
Lien vers le frame "Security" est KO 

![image.png](https://zube.io/files/lead-wire/9da81d6a60553a2fe4b63e09c0a80f0b-image.png)

Lien vers les frames "Add New Dashboard" : Il y a un message d'erreur
![image.png](https://zube.io/files/lead-wire/2d9103b61eae472b95aada80f8e103c2-image.png)

**Comment by hameddhib** [comment]
est ce que le token est dans le bon endroit ?

https://kibana.test.leadwire.io:443/app/dashboards#/create?app/kibana?security_tenant=admin&_g=()&_a=(description:'',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),panels:!(),query:(language:kuery,query:''),timeRestore:!f,title:'',viewMode:edit)
