### ISSUE TITLE
Time Box / Kibana frame

### ISSUE THREAD

**Issue by WassimDhib** [leadwire-apm/leadwire-portail#224]
Quand on change le timerange, le dashboard se recharge et on perd le paramètre embed=true

![image](https://user-images.githubusercontent.com/30473593/103307680-f9741a80-4a10-11eb-9772-376af847c8cd.png)

**Comment by WassimDhib** [comment]
@hameddhib  à clôturer suite au passage à reactJS ?

**Comment by hameddhib** [comment]
Tu peux clôturé
