### ISSUE TITLE
[EVOL] Organizations

### ISSUE THREAD

**Issue by leadwire-apm** [leadwire-apm/leadwire-portail#237]
Ajouter une nouvelle entité "Organization" 

**Relations** 
- Un utilisateur appartient à 0 ou à plusieures Organizations 
- Une application appartient à une et une seule Organization

**Attributs**
- name
- id
- owner
- description

**Créer un écran de gestion (menu admin)**
- Créer une Organization
- Edit Organizations (seule la description est modifiable)
- Delete Organization (Seulement si aucune application n'est rattachée et aucun user n'est rattaché en dehors du owner)

**Créer un écran de gestion (menu user)**
- Le owner de l'organization peut inviter un user à rejoindre son organization 
- Le owner de l'organization peut exclure un user de son organization
- Un user peut se retirer d'une organization
- Un user peut sélectionner une et une seule organization "courante" (par défaut la première organization  qui a été affectée est marquée comme "courante"

**Règles de gestion**
Le user ne peut être invité qu'à des applications qui appartiennent à son organization 
Si le user est exclut d'une organization, il est automatiquement retiré de toutes les applications de cette organization 

**Créer un objet opendistro (role) pour l'organization**
- Tous les users rattachés à cette organization obtiennent ce role opendistro.

**Créer un objet ldap (role)**
```
dn: cn=organization,ou=apm,ou=roles,dc=leadwire,dc=io
objectClass: organizationalRole
objectClass: top
cn: organization
ou: organization
roleOccupant: cn=tuser,ou=people,dc=leadwire,dc=io
roleOccupant: cn=tuser2,ou=people,dc=leadwire,dc=io
```

**Comment by WassimDhib** [comment]
traité partiellement par #244
